# Generated by Django 5.2.7 on 2025-11-05 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchaSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(default='Irvine', max_length=100)),
                ('state', models.CharField(default='CA', max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('hours', models.CharField(blank=True, help_text="e.g., 'Mon-Fri: 9AM-9PM, Sat-Sun: 10AM-10PM'", max_length=200)),
                ('price_range', models.CharField(blank=True, choices=[('$', '$ - Inexpensive'), ('$$', '$$ - Moderate'), ('$$$', '$$$ - Expensive'), ('$$$$', '$$$$ - Very Expensive')], max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='matcha_spots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Matcha Spot',
                'verbose_name_plural': 'Matcha Spots',
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
    ]
